[package]
name = "tomatify"
version = "0.1.0"
edition = "2021"
description = "A tomato clock daemon written in Rust"

[dependencies]
mockall = "0.13.0"
snafu = "0.8.4"
tokio = { version = "1.39.2", features = ["full", "tracing"] }
tracing = "0.1.40"
