name: Test

on:
  - push
  - pull_request

env:
  DEV_SHELL_NAME: ci
  CARGO_TERM_COLOR: always

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: nixbuild/nix-quick-install-action@v28

      - name: Cache Nix Store
        uses: nix-community/cache-nix-action@v5.2.1
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1073741824
          purge: true
          purge-prefixes: cache-${{ runner.os }}-
          purge-created: 0
          purge-primary-key: never

  check:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore Cache
        uses: Swatinem/rust-cache@v2.7.3

      - name: Check
        run: cargo check

      - name: Check Clippy
        run: cargo clippy

      - name: Format
        run: cargo fmt --all -- --check

  test:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore Cache
        uses: Swatinem/rust-cache@v2.7.3

      - name: Test
        run: cargo test
